"""
Django settings for sarahah project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

<<<<<<< HEAD
=======

>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'akk)71u_c@%#ejy8ufrwbu7(013*)661jbaf)y^&wzmqb$j4hg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
=======

>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bootstrap3',
    'sarahah.core',
    'sarahah.accounts',
    'sarahah.smessages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sarahah.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sarahah.wsgi.application'

<<<<<<< HEAD
=======

>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

<<<<<<< HEAD
=======

>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD
=======

>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

<<<<<<< HEAD
=======

>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'sarahah', 'media')
MEDIA_URL = '/media/'

LOGIN_URL = "account:login"
LOGIN_REDIRECT_URL = "account:dashboard"
LOGOUT_URL = "account:logout"
<<<<<<< HEAD
LOGOUT_REDIRECT_URL = "core:home"
AUTH_USER_MODEL = 'accounts.User'
EMAIL_BACKEND='django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST="smtp.zoho.com.au"
EMAIL_PORT=465
EMAIL_USE_SSL=True
EMAIL_HOST_USER="mail@fintop.com.au"
DEFAULT_FROM_EMAIL="Fintop <mail@fintop.com.au>"
#EMAIL_HOST_PASSWORD="SL@Top1Day"
EMAIL_HOST_PASSWORD="HHgcLSz4Ws9E"
=======
AUTH_USER_MODEL = 'accounts.User'
>>>>>>> 02ac08a5e02b8c2bb1451d42ec17bf3afa8b0827
