# Generated by Django 3.0.8 on 2021-04-03 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, upload_to='message/posts', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(blank=True, help_text='You have 255 characters remaining', max_length=255, verbose_name='Message'),
        ),
    ]
