# Generated by Django 3.0.8 on 2021-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0002_auto_20210403_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message/posts', verbose_name='Posts'),
        ),
    ]
