# Generated by Django 3.0.8 on 2021-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0004_auto_20210403_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='message/posts', verbose_name='Picture '),
        ),
    ]
