# Generated by Django 3.0.8 on 2021-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0007_auto_20210403_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='editedpic',
            field=models.ImageField(blank=True, null=True, upload_to='message/edit'),
        ),
    ]
