# Generated by Django 3.1.4 on 2021-04-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0008_messages_editedpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='editedpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
