# Generated by Django 3.1.4 on 2021-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0009_auto_20210404_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='editedpic',
        ),
    ]
