# Generated by Django 3.1.4 on 2021-04-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0012_auto_20210404_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editedMessage',
        ),
    ]
