# Generated by Django 3.1.4 on 2021-04-04 11:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smessages', '0013_delete_editedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='editpic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='message/posts'),
        ),
    ]
